package gogen

// Code generated by mkfunccontrolparamtype DO NOT EDIT.
// with parameters set at:
//	command line:2: -d This determines whether or not a go subcommand should be run with its output displayed
//	command line:4: -t CmdIO
//	command line:6: -v NoCmdIO
//	command line:8: -v ShowCmdIO

// CmdIOType This determines whether or not a go subcommand should be run with its output displayed
// Generated Code
type CmdIOType int

// Set the lower sentinel value to minus one so that the default (0)
// value is the first meaningful entry
const (
	MinValForCmdIOType CmdIOType = iota - 1
	NoCmdIO
	ShowCmdIO
	MaxValForCmdIOType
)

// IsValid is a method on the CmdIOType type that can be used
// to check a received parameter for validity. It compares
// the value against the sentinel values for the type
// and returns false if it is outside the valid range
func (v CmdIOType) IsValid() bool {
	if v <= MinValForCmdIOType {
		return false
	}
	if v >= MaxValForCmdIOType {
		return false
	}
	return true
}
