package gogen

// Code generated by mkfunccontrolparamtype; DO NOT EDIT.
// with parameters set at:
//	[command line]: Argument:2: "-d" "determines whether or not a go subcommand should be run with its output displayed. You can also choose to not show IO on failure"
//	[command line]: Argument:4: "-t" "CmdIO"
//	[command line]: Argument:6: "-v" "NoCmdIO"
//	[command line]: Argument:8: "-v" "ShowCmdIO"
//	[command line]: Argument:10: "-v" "NoCmdFailIO"

/*
CmdIOType determines whether or not a go subcommand should be run with its
output displayed. You can also choose to not show IO on failure
*/
type CmdIOType int

// These constants are the allowed values of CmdIOType
const (
	NoCmdIO CmdIOType = iota
	ShowCmdIO
	NoCmdFailIO
)

// IsValid is a method on the CmdIOType type that can be used
// to check a received parameter for validity. It compares
// the value against the boundary values for the type
// and returns false if it is outside the valid range
func (v CmdIOType) IsValid() bool {
	if v < NoCmdIO {
		return false
	}

	if v > NoCmdFailIO {
		return false
	}

	return true
}
